apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: spring-petclinic
          image: docker.io/st251/petclinic:62
          ports:
            - name: web
              containerPort: 8181
          env:
            - name: SPRING_PROFILES_ACTIVE 
              value: mysql
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: url 
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: password 
