apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: prod
spec:
  encryptedData:
    password: AgB9/fkqMkUU6nDzyJNPRNsHhq3tq+jpqVZJ6n0NFn3TSqb2jk2mvuQkBicciUR4ako9UAMsJ+68u66PPnqxUPq8v5jdYUDg11ZvEq/QaQpToB3LZ1YNZYBolttzxwgOr7xHEOkZThF24YPO9hIVyXt3xGw5ZZHYMH2sXBY+rYWRRyJJtQFZhMG5ueTvE+EgOhx1V0Kb2oDnpIp6CX3JUQMd3dhsr4mHeqWjujR2cLArveLZ+hwN4kKL0sZF7RizbspTpxb9O3xltHUKhkg5DtaH6hhs4RUnsGJpQRsF/6xYieS9TZb50YIi3i+Xict1PvNryEm0kGbwP4cNJemzqyf6gFAzGrl3vgbZXkpk9M11d2uTeWhhM403XZXr2dMC29mYJtuQqtog3kfPCdA6FhPGbY7qycT6WfkDNyOTk4lXmj9b70LgH9Rycqo/2XZKuUe8bU1skxe+xxcAWwGjvajaZMfGpsFLQbuEKbC6Ane1zYj82kf9V9ZVJA6eHY4C9lVOpJEigse7GgKCtrDYGuNSUMVR1K+dC2UXzWLzonbrcNEJOvbMWHQD/nUmVGxl9yF+ge/v+EV9fX47SP5SCowdNZ+8AJOH2lQAzprB1f8txJSe53RmBbJacEjcS3TYuaKLOzSZP/2oR9psenbzndS43ZhdSo0oVpzRkupTZA2ulTyoA5LCaIXisZkb9mOwZIWCnkh3sd6tiGE=
    url: AgBHh3WWus9OHxsYJdBo+KPahBVR17RnRxyHMa/w2qSMtDr2udQj2FACUk5sJou/5FwiXPP3EtRg+bYl4ksg4uMxqlSXQ6SVl4C/qItYiX6RQd8uR3sDXRF17jfwhJALavVhr5SUWQvh+BialjgbDzJItJSWPjATNHFlV88D9SeyRQ8KIGDkyZftdlkUSrNj5DqKGUA9P6DFF1Ddy2mdFSKWNRe3GgCDmLayySlcab2rbShOJ5S3lofJ4Oz6QsxOCof7LDRd/+Y7q25wJ8eBjFxx4XpNr0rI9AYFo8sgpVxcnam1wO2NMZJ8oiraU1ZEY646CQGTFy623TIUR25oPlBVbs5n3Y3OOzLThNjZvsnKZdnesnMuIppxD7eaZ70Dbrvet5cR11SVlBJUahEeemaKJczQKBiUBKlEqz/xQFGvp+TFHfVUGR4DuS/VuUWSH6Tlw9RMcVTK6eJD/g1+gsg2pGqXgM5eFULQ3umR+HQKjhMnJv5ofENJ0l1DbkKbKolcXcZqONYpLT9Bc9rqzav3iA/p8bpnhoshoPYH00IT825JdXQLPBlsKKCm8O+OB1/XH0SILW7aoVQma0Vjh1lkMs+etiDnEdlyMP0l6RG3rdKW9xhf6dqmlaeHhQuckjt8oqSHc8K2efEo0/0n2KWwzMB4G5JV+fvSBvfSRjf35VRRembELs4BITgG/RqY7oYOujaq7Eo3uoC1yohpY2qTCPJLBL8xGjkvDb23/TZoT0RLT9iXidYUhatdwy8SgC2mMA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: prod

